### ISSUE TITLE
Thank you for the author's outstanding work. Your paper's visualization is very beautiful. May I ask if you could provide the visualization code?

### ISSUE THREAD

**Issue by zhoulian-sudo** [xupei0610/ContextVAE#1]
Thank you for the author's outstanding work. Your paper's visualization is very beautiful. May I ask if you could provide the visualization code?Thanks.

**Comment by xupei0610** [comment]
The APIs from different datasets differ a lot. For example, nuScenes directly provides the API to get semantic maps, while for  Lyft (having an overview map) and Waymo (only having the local map for each scenario), we have to draw road lines by ourselves.

Here is a script that I used to visualize the map of nuScenes. Hope it could be helpful
https://gist.github.com/xupei0610/98d99b1b62ced0bce55d181ed331fe89

**Comment by xupei0610** [comment]
If you have additional questions about visualization, you can reach me by my email, which you can find from my website https://pei-xu.github.io/.

Thank you.

**Comment by xmccl** [comment]
Hello, dear author, I have a problem formhttps://gist.github.com/xupei0610/98d99b1b62ced0bce55d181ed331fe89, can you provide the method to get DATA_PATH?
