### ISSUE TITLE
ModuleNotFoundError: No module named 'nuscenes.nuscenes'; 'nuscenes' is not a package

### ISSUE THREAD

**Issue by EXGHLI** [xupei0610/ContextVAE#2]
I've run pip install nuscenes-devkit. Still getting error:
ModuleNotFoundError: No module named 'nuscenes.nuscenes'; 'nuscenes' is not a package
How can I solve this problem?

**Comment by xupei0610** [comment]
I just checked. There is no problem to install the package of nuScenes via pip. 

If you still have the problem, please consult on nuScenes repo (https://github.com/nutonomy/nuscenes-devkit). You can also find a tutorial here (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb).

**Comment by xupei0610** [comment]
Forgot to mention.

Do  you have any file or folder in the name of `nuscenes` ? This is another reason that could cause import error in Python.

**Comment by EXGHLI** [comment]
Can you tell me what the data set structure is?
Thank you.

徐霈 (Pei Xu) ***@***.***> 於 2024年3月17日 週日 21:11 寫道：
