### ISSUE TITLE
Taining time 

### ISSUE THREAD

**Issue by Pranav-chib** [xupei0610/ContextVAE#3]
Hi author thankyou for the wonderfull work can you let me know the training time, how much time will it take to train ContextVAE on each dataset. 
Thankyou

**Comment by xupei0610** [comment]
Training on nuScenes can be done quickly with around 2 hours (a v100 GPU).
Training on Lyft takes around two days with 4 x A100.
Training on Waymo takes around two days with 8 x A100.

**Comment by xmccl** [comment]
Can you download the lyft data set using https://lyft-l5-datasets-public.s3-us-west-2.amazonaws.com? I seem to have encountered a problem. If you have downloaded the data set locally, can you provide a link to the network disk? Thank you very much

**Comment by xmccl** [comment]
Can you download the lyft datasets using https://lyft-l5-datasets-public.s3-us-west-2.amazonaws.com? I seem to have encountered a problem. If you have downloaded the datasets locally, can you provide a link to the Baidu network disk? Thank you very much
