### ISSUE TITLE
How to download lyft datasets

### ISSUE THREAD

**Issue by xmccl** [xupei0610/ContextVAE#4]
Hello, author, thank you for your excellent work. The link https://lyft-l5-datasets-public.s3-us-west-2.amazonaws.com you provided in the readme seems to have permission issues or has expired. How did you download the lyft L5 prediction dataset?

**Comment by xupei0610** [comment]
You can find the details of the Lyft Level 5 Prediction Dataset from their project webpage (https://woven-planet.github.io/l5kit/dataset.html). You may find help downloading the dataset there.

**Comment by xmccl** [comment]
Thank you for your help, at the same time, I have another question in your main.py . It seems that changing the defaults of the device in py does not specify multiple gpus for training. How can I set the value of the device for multi-gpu training?

**Comment by xmccl** [comment]
I am a student, feel your work is very good, hope to have the opportunity to consult you, the following is my mobile phone number: 17886965197, hope to add your wechat.
